# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger: none 

variables:
- name: TAG
  value: ""
jobs:
- job: DeploymentJob
  pool:
   vmImage: ubuntu-latest
  steps:
  # - task: DownloadPipelineArtifact@2 
  #   inputs: 
  #     buildType: 'specific'
  #     project: 'a7a9079d-03ad-44f5-8677-e9ec44b5ba3d' 
  #     definition: '12' 
  #     specificBuildWithTriggering: true
  #     buildVersionToDownload: 'latest'
  #     allowPartiallySucceededBuilds: true 
  #     allowFailedBuilds: true 
  #     artifactName: 'manifest'
  #     targetPath: '$(Pipeline.Workspace)'
  #   continueOnError: true

  - script: |
     wget https://raw.githubusercontent.com/Priyasunil26/Sales-desk-automation-pipeline/main/param_value.txt -O $(Pipeline.Workspace)/param_value.txt
     ls $(Pipeline.Workspace)
     pwd
     echo "whare I am in"
    displayName: 'Assign k8s values'

  - script: |
      KubernetesSiteUpdate=$(awk '/Kubernetes:/ {print $2}' $(Pipeline.Workspace)/param_value.txt)
      echo "$KubernetesSiteUpdate"
      echo "##vso[task.setvariable variable=Updatek8ssite]$KubernetesSiteUpdate"
      BranchName=$(awk '/Branch:/ {print $2}' $(Pipeline.Workspace)/param_value.txt)
      echo "$BranchName"
      echo "##vso[task.setvariable variable=Branch]$BranchName"
    displayName: 'Read Param Value'

  - script: |
      KubernetesSiteUpdate=$(awk '/Kubernetes:/ {print $2}' $(Pipeline.Workspace)/param_value.txt)
      echo "$KubernetesSiteUpdate"
      echo "##vso[task.setvariable variable=Updatek8ssite]$KubernetesSiteUpdate"
      BranchName=$(awk '/Branch:/ {print $2}' $(Pipeline.Workspace)/param_value.txt)
      echo "$BranchName"
      echo "##vso[task.setvariable variable=Branch]$BranchName"
    displayName: 'Assign k8s values'

  - script: cat $(Pipeline.Workspace)/param_value.txt
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
          if [ -f $(Pipeline.Workspace)/param_value.txt ]; then
            URL=$(awk '/KubernetesPackage:/ {print $2}' $(Pipeline.Workspace)/param_value.txt)
            echo "Text File URL: $URL"
            IMAGE_TAG=$(echo "$URL" | grep -oP 'Linux_Kubernetes_\K[\d\.]+_\d{8}_\d{6}')
            echo "##vso[task.setvariable variable=TAG]$IMAGE_TAG"
            echo Y | gcloud auth configure-docker us-central1-docker.pkg.dev
            sudo wget $URL
            sudo rm -rf $(Pipeline.Workspace)/param_value.txt
            sudo apt install unzip 
            sudo unzip BoldBIEnterpriseEdition_Linux_*
            echo Y | gcloud auth configure-docker us-central1-docker.pkg.dev
          else
            echo "Bold BI Kubernetes Linux Package Does Not Exist"
          fi
    continueOnError: true
    
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Pipeline.Workspace)'
      Contents: '**/data-scheduler.dockerfile'  # Path to the file you want to move
      TargetFolder: '$(Pipeline.Workspace)/BoldBIEnterpriseEdition-Linux'
    displayName: 'Move content to designer-viewer file'
    continueOnError: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Pipeline.Workspace)'
      Contents: '**/designer-viewer.dockerfile'  # Path to the file you want to move
      TargetFolder: '$(Pipeline.Workspace)/BoldBIEnterpriseEdition-Linux' 
    displayName: 'Move content to designer-viewer file'
    continueOnError: true    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo mkdir -p $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/data-scheduler
        sudo cp -r $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/dataservice/* $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/data-scheduler/
        sudo mkdir -p $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/viewer
        sudo cp -r $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/dataservice/* $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/viewer/
        ls $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/data-scheduler
        echo **********
        ls $(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/viewer
    displayName: 'Creating a folder and moving files'
    continueOnError: true

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        APP_SETTINGS_FILE="$(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/data-scheduler/appsettings.json"
        NEW_APP_PATH="\/bi\/data-scheduler"
        NEW_LOGGER_NAME="bi.data-scheduler"

        sudo sed -i 's/"AppPath":.*/"AppPath": "'"$NEW_APP_PATH"'",/' "$APP_SETTINGS_FILE"
        sudo sed -i 's/"Loggername":.*/"Loggername": "'"$NEW_LOGGER_NAME"'",/' "$APP_SETTINGS_FILE"
    displayName: 'Updating properties in data-scheduler appsettings'    
    continueOnError: true

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        APP_SETTINGS_FILE="$(Pipeline.Workspace)/s/BoldBIEnterpriseEdition-Linux/application/bi/viewer/appsettings.json"
        NEW_APP_PATH="\/bi\/viewer"
        NEW_LOGGER_NAME="bi.viewer"

        sudo sed -i 's/"AppPath":.*/"AppPath": "'"$NEW_APP_PATH"'",/' "$APP_SETTINGS_FILE"
        sudo sed -i 's/"Loggername":.*/"Loggername": "'"$NEW_LOGGER_NAME"'",/' "$APP_SETTINGS_FILE"
    displayName: 'Updating properties in viewer appsettings'    
    continueOnError: true

  - task: Docker@2
    inputs:
      containerRegistry: 'Artifect_Registry'
      repository: 'boldbi-294612/boldbi/bi-dataservice-datascheduler'
      command: 'build'
      Dockerfile: BoldBIEnterpriseEdition-Linux/data-scheduler.dockerfile
      tags: '$(TAG)_dev'
    displayName: Docker Build Id-Web Image
    continueOnError: true
            
  - task: Docker@2
    inputs:
      containerRegistry: 'Artifect_Registry'
      repository: 'boldbi-294612/boldbi/bi-dataservice-datascheduler'
      command: 'push'
      tags: '$(TAG)_dev'
    displayName: Docker push Id-Web Image
    continueOnError: true

  - task: Docker@2
    inputs:
      containerRegistry: 'Artifect_Registry'
      repository: 'boldbi-294612/boldbi/bi-dataservice-viewer'
      command: 'build'
      Dockerfile: BoldBIEnterpriseEdition-Linux/data-scheduler.dockerfile
      tags: '$(TAG)_dev'
    displayName: Docker Build Id-Web Image
    continueOnError: true
  - task: Docker@2
    inputs:
      containerRegistry: 'Artifect_Registry'
      repository: 'boldbi-294612/boldbi/bi-dataservice-viewer'
      command: 'push'
      tags: '$(TAG)_dev'
    displayName: Docker push Id-Web Image
    continueOnError: true
